name: Test backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-backend:
    defaults:
      run:
        working-directory: './backend'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies PHP
        id: php-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: dependencies-php-composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug

      - name: Set up Node & NPM
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install PHP dependencies
        if: steps.php-cache.outputs.cache-hit != 'true'
        run: composer install --no-interaction --no-progress --ansi
      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build dependencies
        run: npm run build

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Tests
        run: composer test